### ISSUE TITLE
Connect failed after enter device password

### ISSUE THREAD

**Issue by daydaychen** [AidanGamzer/ReRa1n#10]
When i run rera1n.sh i get some errors
rera1n.sh
```
kex_exchange_identification: Connection closed by remote host
kex_exchange_identification: Connection closed by remote host
```
forward.sh
```
Forwarding local port 2222 to remote port 22
Incoming connection to 2222
Waiting for devices...
Connecting to device <MuxDevice: ID 1 ProdID 0x12a8 Serial '4fa027c569ceb9ffb082cf07a38e0aa8252045d8' Location 0x10009>
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 33528)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "tcprelay.py", line 82, in handle
    dsock = mux.connect(dev, self.server.rport)
  File "/usr/bin/iphonessh/python-client/usbmux.py", line 235, in connect
    return connector.connect(device, port)
  File "/usr/bin/iphonessh/python-client/usbmux.py", line 206, in connect
    raise MuxError("Connect failed: error %d"%ret)
MuxError: Connect failed: error 3
----------------------------------------
```

How i can fix it?
OS: Kali Linux 2019.04

**Comment by sillydog825** [comment]
you can manually use ssh -v option to accept ios authentication keys, then reruning ssh will work. By the way, is this tool can downgrade jailbreaked iphone ? I can't find any option to do this.

**Comment by daydaychen** [comment]
Thanks, this i don't konw.

**Comment by daydaychen** [comment]
> you can manually use ssh -v option to accept ios authentication keys, then reruning ssh will work. By the way, is this tool can downgrade jailbreaked iphone ? I can't find any option to do this.

Thanks, this i don't konw.

**Comment by slaesh** [comment]
try running on port 44

**Comment by hustwyk** [comment]
ReRa1n uses [`iphonessh`](https://github.com/rcg4u/iphonessh) to connect iPhone. In iphonessh repo, you can see, the way using USB is only available for an existing OpenSSH on the iPhone, so it requires a jailbroken iPhone....
